import type { Decision } from "@/types";

function d(decisions: Decision[], section: string, key: string): string {
  const found = decisions.find((dec) => dec.section === section && dec.key === key);
  return found?.value ?? "[NOT SPECIFIED]";
}

/**
 * Generate a plain-English Guardianship Designation document from
 * the user's decisions.
 */
export function generateGuardianshipText(decisions: Decision[]): string {
  const testatorName = d(decisions, "family", "full_name");
  const partnerName = d(decisions, "family", "partner_name");
  const children = d(decisions, "family", "children");
  const primaryGuardian = d(decisions, "guardianship", "primary_guardian");
  const backupGuardian = d(decisions, "guardianship", "backup_guardian");
  const namedIndividually = d(decisions, "guardianship", "guardian_named_individually");
  const specialWishes = d(decisions, "guardianship", "special_wishes");
  const talkedToGuardian = d(decisions, "guardianship", "talked_to_guardian");

  return `
================================================================================
              DRAFT DOCUMENT - FOR ATTORNEY REVIEW ONLY
================================================================================

                 GUARDIANSHIP DESIGNATION
                          FOR
              THE MINOR CHILDREN OF
              ${testatorName.toUpperCase()}${partnerName !== "[NOT SPECIFIED]" ? ` AND ${partnerName.toUpperCase()}` : ""}

State of Texas


DECLARATION OF GUARDIANSHIP PREFERENCES
----------------------------------------

We, ${testatorName}${partnerName !== "[NOT SPECIFIED]" ? ` and ${partnerName}` : ""}, residents of the
State of Texas, hereby declare our preferences for the guardianship of our
minor children in the event that ${partnerName !== "[NOT SPECIFIED]" ? "both of us are" : "I am"} unable to care
for them.

Our children: ${children}


PRIMARY GUARDIAN
----------------

We designate ${primaryGuardian} as the primary guardian of our minor children.

${namedIndividually !== "[NOT SPECIFIED]" ? `Guardian named individually (not as a couple): ${namedIndividually}` : ""}

${talkedToGuardian !== "[NOT SPECIFIED]" ? `We have discussed this with the proposed guardian: ${talkedToGuardian}` : ""}


BACKUP GUARDIAN
---------------

If ${primaryGuardian} is unable or unwilling to serve as guardian, we designate
${backupGuardian} as the backup guardian with the same responsibilities.


SPECIAL WISHES AND INSTRUCTIONS
--------------------------------

${specialWishes !== "[NOT SPECIFIED]" ? specialWishes : "No special wishes were specified during the planning session."}


GENERAL GUIDANCE FOR THE GUARDIAN
---------------------------------

We ask that our guardian:

  1. Keep our children together whenever reasonably possible.

  2. Maintain our children's existing relationships with extended family,
     including grandparents, aunts, uncles, and cousins on both sides of
     the family.

  3. Support our children's current school, activities, and friendships to
     the extent practical.

  4. Use any funds set aside in our will or trust for our children's health,
     education, and general well-being.

  5. Raise our children with love and provide a stable, nurturing home.


LEGAL NOTES
------------

This document expresses our wishes regarding guardianship. Under Texas law
(Texas Estates Code, Chapter 1104), a parent may designate a guardian for
their minor children by written declaration. A court will give weight to this
designation but retains discretion to act in the best interests of the child.

This designation does not create a binding legal obligation. It is intended to
guide the court and family members in understanding our wishes.


SIGNATURES
----------

Parent 1: ________________________________________
Printed name: ${testatorName}
Date: ____________________

${partnerName !== "[NOT SPECIFIED]" ? `Parent 2: ________________________________________
Printed name: ${partnerName}
Date: ____________________` : ""}


WITNESS 1:

Signature: ________________________________________
Printed name: ________________________________________
Date: ____________________


WITNESS 2:

Signature: ________________________________________
Printed name: ________________________________________
Date: ____________________


NOTARY ACKNOWLEDGMENT

STATE OF TEXAS
COUNTY OF ____________________

Subscribed and sworn to before me on this ______ day of ____________, 20____.

Notary Public signature: ________________________________________
My commission expires: ____________________

[NOTARY SEAL]

================================================================================
              DRAFT DOCUMENT - FOR ATTORNEY REVIEW ONLY
  This document was generated by WillBuddy as a starting point for your
  estate plan. It is NOT legal advice. Please have a licensed Texas estate
  planning attorney review and finalize this document before signing.
================================================================================
`.trim();
}
