/** Structured block for PDF rendering (parsed from plain-text templates). */
export type PdfBlock =
  | { type: "docTitle"; text: string }
  | { type: "heading"; text: string }
  | { type: "subheading"; text: string }
  | { type: "paragraph"; text: string }
  | { type: "listItem"; text: string }
  | { type: "signature"; label: string; value?: string };

const DECORATIVE_LINE = /^[\s=*\-_]+$/;
const DRAFT_BANNER = /DRAFT DOCUMENT|FOR ATTORNEY REVIEW ONLY/i;
const FOOTER_BANNER = /generated by WillBuddy|NOT legal advice/i;
const ARTICLE_HEADING = /^(ARTICLE|PART|SECTION)\s+\d+/i;
const SIGNATURE_LINE = /^_{5,}$/;
const LABELED_FIELD = /^(.+?):\s*(_{3,}|[^\n]+)$/;

function isBannerLine(line: string): boolean {
  const t = line.trim();
  return DRAFT_BANNER.test(t) || FOOTER_BANNER.test(t);
}

function isSubheading(line: string): boolean {
  const t = line.trim();
  if (t.length < 4 || t.length > 72) return false;
  if (/[a-z]/.test(t)) return false;
  if (DECORATIVE_LINE.test(t)) return false;
  if (ARTICLE_HEADING.test(t)) return false;
  if (t.startsWith("STATE OF") || t.startsWith("COUNTY OF")) return false;
  return /^[A-Z0-9][A-Z0-9\s,&;()—\-'/.]+$/.test(t);
}

function isDocTitle(line: string, index: number): boolean {
  if (index > 12) return false;
  const t = line.trim();
  if (t.length < 8 || t.length > 64) return false;
  if (/[a-z]/.test(t)) return false;
  if (DECORATIVE_LINE.test(t)) return false;
  return (
    t.includes("WILL") ||
    t.includes("GUARDIAN") ||
    t.includes("ATTORNEY") ||
    t.includes("HIPAA") ||
    t.includes("DIRECTIVE") ||
    t.includes("AUTHORIZATION")
  );
}

function normalizeWhitespace(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * Convert plain-text template output into structured PDF blocks.
 * Strips ASCII decorations and duplicate draft banners.
 */
export function parseDocumentBody(raw: string): PdfBlock[] {
  const lines = raw.split("\n");
  const blocks: PdfBlock[] = [];
  let paragraph: string[] = [];
  let seenContent = false;
  let docTitleCount = 0;

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    const text = normalizeWhitespace(paragraph.join(" "));
    if (text) blocks.push({ type: "paragraph", text });
    paragraph = [];
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      flushParagraph();
      continue;
    }

    if (DECORATIVE_LINE.test(trimmed) || isBannerLine(trimmed)) {
      flushParagraph();
      continue;
    }

    if (trimmed.startsWith("[NOTARY SEAL]")) {
      flushParagraph();
      blocks.push({ type: "signature", label: "Notary seal" });
      continue;
    }

    const fieldMatch = trimmed.match(LABELED_FIELD);
    if (fieldMatch && fieldMatch[2].includes("_")) {
      flushParagraph();
      blocks.push({
        type: "signature",
        label: fieldMatch[1].trim(),
      });
      continue;
    }

    if (SIGNATURE_LINE.test(trimmed)) {
      flushParagraph();
      const prev = lines[i - 1]?.trim() ?? "";
      blocks.push({
        type: "signature",
        label: prev && !DECORATIVE_LINE.test(prev) ? prev : "Signature",
      });
      continue;
    }

    if (ARTICLE_HEADING.test(trimmed)) {
      flushParagraph();
      blocks.push({ type: "heading", text: trimmed });
      seenContent = true;
      continue;
    }

    if (!seenContent && isDocTitle(trimmed, i) && docTitleCount < 2) {
      flushParagraph();
      blocks.push({ type: "docTitle", text: trimmed });
      docTitleCount++;
      continue;
    }

    if (isSubheading(trimmed)) {
      flushParagraph();
      blocks.push({ type: "subheading", text: trimmed });
      seenContent = true;
      continue;
    }

    if (/^\d+\.\s/.test(trimmed) || /^\s{2,}\d+\./.test(line)) {
      flushParagraph();
      blocks.push({
        type: "listItem",
        text: normalizeWhitespace(trimmed.replace(/^\d+\.\s*/, "")),
      });
      seenContent = true;
      continue;
    }

    if (/^\s{2,}\S/.test(line) && trimmed.includes(":")) {
      flushParagraph();
      blocks.push({ type: "listItem", text: trimmed });
      seenContent = true;
      continue;
    }

    if (trimmed === "State of Texas") {
      flushParagraph();
      blocks.push({ type: "paragraph", text: trimmed });
      seenContent = true;
      continue;
    }

    paragraph.push(trimmed);
    seenContent = true;
  }

  flushParagraph();
  return blocks;
}
