import type { Metadata } from "next";
import Link from "next/link";
import { getSupportEmail } from "@/lib/resend";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "WillBuddy terms for voice-first estate planning preparation and draft documents.",
};

const updated = "June 11, 2026";

export default function TermsPage() {
  const supportEmail = getSupportEmail();

  return (
    <main className="flex-1 px-6 py-16 md:py-24">
      <article className="mx-auto max-w-3xl">
        <p className="mb-4 text-sm uppercase tracking-widest text-[#9B8E7E]">
          Terms
        </p>
        <h1 className="mb-4 font-[family-name:var(--font-heading)] text-3xl font-bold text-[#2D2A26] md:text-4xl">
          Terms of Service
        </h1>
        <p className="mb-10 text-sm text-[#9B8E7E]">Last updated {updated}</p>

        <div className="space-y-8 text-sm leading-relaxed text-[#5B4F3E] md:text-base">
          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              Not Legal Advice
            </h2>
            <p>
              WillBuddy is not a law firm, does not provide legal advice, and
              does not create an attorney-client relationship. Draft documents
              and summaries generated by WillBuddy should be reviewed,
              finalized, and executed with a licensed estate-planning attorney.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              Texas Scope
            </h2>
            <p>
              WillBuddy is currently designed for Texas estate-planning
              preparation. Estate law varies by state, and users outside Texas
              should not rely on WillBuddy draft documents for their state.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              User Responsibilities
            </h2>
            <p>
              You are responsible for providing accurate information, reviewing
              generated drafts, choosing whether to share documents, and working
              with a qualified attorney for legal review, signing, witnessing,
              notarization, and any required filing.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              Payments
            </h2>
            <p>
              Payments are processed by Stripe. Prices and availability may
              change, but checkout should show the current amount before a
              payment is completed.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              Availability
            </h2>
            <p>
              WillBuddy may change, pause, or discontinue features. AI-generated
              output can be incomplete or inaccurate and must be reviewed before
              use.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-[family-name:var(--font-heading)] text-xl font-bold text-[#2D2A26]">
              Contact
            </h2>
            <p>
              Questions about these terms can be sent through the{" "}
              <Link
                className="font-semibold text-[#2D2A26] underline decoration-[#CDBFAE] underline-offset-4"
                href="/contact"
              >
                contact form
              </Link>{" "}
              or by email at{" "}
              <a
                className="font-semibold text-[#2D2A26] underline decoration-[#CDBFAE] underline-offset-4"
                href={`mailto:${supportEmail}`}
              >
                {supportEmail}
              </a>
              .
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
